### ISSUE TITLE
IB Designables issue

### ISSUE THREAD

**Issue by chumps52** [rootstrap/RSFormView#29]
When adding a FormView, I get the following error:

<img width="1165" alt="Screenshot 2019-06-12 at 11 00 59" src="https://user-images.githubusercontent.com/22566395/59342321-75105880-8d01-11e9-9cc7-8a071a15e5ce.png">

I have tried cleaning the project, as well as deleting all derived data. I have also tried `pod deintegrate` followed by `pod install`. This happened on both 1.0.1 and 1.1.0.

This is how I have RSFormView set up in Storyboard:
<img width="1411" alt="Screenshot 2019-06-12 at 11 00 00" src="https://user-images.githubusercontent.com/22566395/59342395-9bce8f00-8d01-11e9-9317-c70a223b28d9.png">

The form still works as expected, just the Storyboard preview is broken.

Also, the README doesn't specify that you have to set the custom module for a FormView to be `RSFormView` - this confused me for a while.

**Comment by germanStabile** [comment]
Hey @chumps52! Thanks for reporting this. 
Are you using dynamic frameworks ? Otherwise add `use_frameworks!` to your pod file. Quit Xcode, and do `pod deintegrate` and `pod install` again and this issue should go away. 
You are right! I missed that on the README will update accordingly.

**Comment by chumps52** [comment]
Hey, I am using them so unfortunately that’s not the issue. My Podfile is as follows:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TAVI Heart Team App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TAVI Heart Team App
  # pod 'IQKeyboardManagerSwift'
  pod 'RealmSwift'
  pod 'IceCream'
  pod 'RxRealm' # Observable objects
  pod 'RxSwift' # Depedency of RxRealm

  pod 'RSFormView'

  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Crashlytics'

end
```

**Comment by germanStabile** [comment]
OK, @glm4 helped me find the issue, we needed to implement `prepareForInterfaceBuilder` in the FormView in order for IB to know how to display the view. I'll be kicking a new version shortly and updating the IB section in the README. Thanks for the heads up!

**Comment by germanStabile** [comment]
Oh, bear in mind that the formView will show as a white view in IB since its not populated at that time

**Comment by chumps52** [comment]
I see, thank you!
Also, I noticed the README still had my references to “max 2 decimal places” etc. - sorry!

**Comment by germanStabile** [comment]
Hey @chumps52, version 1.1.1 should fix this issue. Let me know how it goes and I'll close this issue.

**Comment by chumps52** [comment]
Hey @germanStabile, unfortunately even after clearing derived data and running `pod deintegrate` and `pod install` (and ensuring I'm on 1.1.1), I'm getting the same issue :/

**Comment by germanStabile** [comment]
It seems to be an issue with Cocoapods https://github.com/CocoaPods/CocoaPods/issues/7606, 
CocoaPods/CocoaPods#7606 (comment) here's a workaround. 
Another workaround would be to wrap RSFormView in your own custom view.

**Comment by germanStabile** [comment]
Closing as this is not an issue specific to this library
