### ISSUE TITLE
Expiration field type formatting and validation.

### ISSUE THREAD

**Issue by kevnm67** [rootstrap/RSFormView#47]
Currently, the ```.expiration``` field type formats numerical input appending a ```/``` between the month and start of the year but allows unlimited character input.  
- What are your thoughts on adding a max character count?  Example result: ```09/2019```. 

Seems as though the expected date format would be either: ```MM/yyyy``` or ```MM/yy```.  Please let me know if I'm misunderstanding this type.

**Comment by kevnm67** [comment]
@germanStabile Sounds good.  I'll make a PR 😉

**Comment by anthfb** [comment]
https://github.com/rootstrap/RSFormView/pull/53

**Comment by kevnm67** [comment]
@anthfb Thanks!  
Sorry for dropping the ball on this.  Been busy with work.

**Comment by glm4** [comment]
@germanStabile we can close this one right?
